

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Image;
                ref class TextBox;
                ref class StackPanel;
            }
        }
    }
}

namespace Csited
{
    partial ref class Profile : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Image^ displayImage;
        private: ::Windows::UI::Xaml::Controls::TextBox^ nameUser;
        private: ::Windows::UI::Xaml::Controls::TextBox^ fechaNacimiento;
        private: ::Windows::UI::Xaml::Controls::TextBox^ ciudad;
        private: ::Windows::UI::Xaml::Controls::TextBox^ email;
        private: ::Windows::UI::Xaml::Controls::TextBox^ fechaCompra;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ tusProductos;
    };
}

