

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "Profile.xaml.h"




void ::App1::Profile::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///Profile.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///Profile.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the ImageBrush named 'displayImage'
    displayImage = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"displayImage"));
}

void ::App1::Profile::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->DoubleTapped +=
            ref new ::Windows::UI::Xaml::Input::DoubleTappedEventHandler(this, (void (::App1::Profile::*)(Platform::Object^, Windows::UI::Xaml::Input::DoubleTappedRoutedEventArgs^))&Profile::Ellipse_DoubleTapped);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(target))->ImageOpened +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::App1::Profile::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&Profile::ImageBrush_ImageOpened);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

